kucherenko/jscpd

- src/jscpd.coffee
Hello,
In my case I had tabs instead of spaces in my `.cpd.yaml`, it was preventing config from loading, but due to error message I spent some time on checking whether I named file correctly.
I propose to extend error message.
> Make error message more clear

- package.json
- scripts/test.sh
Preventing failing `npm run test` on Windows (required bash). Has been tested only on Arch Linux so far, and Windows 8.1 with gitbash.
> Tests for Windows

- README.md
- src/report.coffee
- test/reporters/cusom.test.coffee
Moving out from reporters as a npm module, doing current working directory relative path `require` instead, works with absolute path as well.
> Custom reporters

- src/jscpd.coffee
We are using `.yml` suffixed-files in our repo, so we thought it would be great if you could support both extensions.  I tested it by moving `test/.cpd.yaml` to `test/.cpd.yml` and running `npm test`.
> Allow for .cpd.yml in addition to .cpd.yaml

- README.md
I'm not sure why, when I leave out the quotes it doesn't find any files. (OS X 10.12, Bash)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/79)
> README: quotes around glob patterns

- src/report.coffee
`path.resolve` is safer than `path.join`.
Relative code: https://github.com/xcatliu/cqc/blob/master/package.json#L27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/111)
> Fix path.join issue

- package.json
- src/preprocessors/files.coffee
There is a problem with excluding. jscpd resolves `exclude` patterns
but there may be cases then `include` and `exclude` options have
no overlap. Also now it calculate difference between 2 lists but it's
slow in case of 2 big lists. This commit use minimatch module (it's
always installed cause it's glob's dependency) for filtering mathed
files. It allow prevent extra sync interaction with fs that should
make jscpd much faster on slow hdd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/122)
> Use minimatch to exclude files

- README.md
- package.json
- scripts/lint.sh
- src/cli/cli.coffee
- src/preprocessors/options.coffee
- src/reporters/_std-log.coffee
- yarn.lock
This PR contains:
- Implement silent mode according to [Avoid print of list of duplication #152](https://github.com/kucherenko/jscpd/issues/152)
- Change the limit type from NUMBER to FLOAT to provide more accurate threshold.
Sometimes the integer threshold not enough to catch code duplication of 50 lines because it less than 1%
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/159)
> Change limit to FLOAT and add silent mode

- src/jscpd.ts
Fix
gitignore pattern with a trailing slash like `node_modules/` is not working
gitignore pattern with a trailing slash like `node_modules/` should work
Issue: https://github.com/kucherenko/jscpd/issues/179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/180)
> fix: add support for trailling slash gitignore pattern

- package-lock.json
- package.json
This is a fix for compatibility with node 12
The library fails to compile with node 12
The app compiles with node 12
This version of level drops support for node 6 which is end of life.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/229)
> upgrade level from 4.0.0 to 5.0.1 for node 12 compatibility

- src/tokenizer/formats/formats.ts
Bug fix.
* **What is the current behaviour?** (You can also link to an open issue here)
Files with the hbs extension are not part of the handlebars format.
* **What is the new behaviour (if this is a feature change)?**
The handlebars format now includes the hbs extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/283)
> fix(handlebars): add hbs file extension

- packages/jscpd/bin/jscpd
- yarn.lock
Fixes https://github.com/kucherenko/jscpd/issues/363
Bugfix
`jscpd.jscpd(process.argv)` returns a Promise, but the rejection(from threshold reporter) is not handled. 
exit with non-zero code when `jscpd.jscpd(process.argv)` rejected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/365)
> handle rejected promise properly (fix #363)

- packages/finder/src/reporters/index.ts
- packages/finder/src/reporters/xcode.ts
- packages/jscpd/__tests__/reporters.test.ts
- packages/jscpd/src/init/reporters.ts
This pull request introduces a Xcode reporter
No Xcode reporter #219 
The new Xcode reporter reports the duplications on the format `full_path_to_file:line:character: warning: {content}`. Where content is the warning message.
Xcode automatically recognizes warnings on this format and highlight the corresponding file.
For Xcode to link to the correct file the full path needs to be provided. Running `jscpd` with the `--absolute` option works, but is there a better way to get the full path, or maybe enforce `--absolute` for this specific …
> Add Xcode reporter

- packages/jscpd/README.md
Documentation
**Other information**:
If you see errors and have a banner instead of a logo for jscpd in Mega-Linter documentation, please notify me :)
https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/copypaste_jscpd.md#readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/406)
> Add Mega-Linter in list of "who uses jscpd"

- packages/tokenizer/src/tokenize.ts
Bug fix
https://github.com/kucherenko/jscpd/issues/421
Even input empty string in calculateLocation(), this function doesn't throw the following error. 
```
TypeError: Cannot read property 'length' of undefined
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/423)
> fix: 🐛 allow empty string in calculateLocation()

- packages/jscpd/package.json
A Security Vuln was identified in the Colors package for >1.4.0, offending packages being `1.4.1`, `1.4.44-liberty`
- [source1](https://twitter.com/snyksec/status/1480286811482206216?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet)
- [source2](https://twitter.com/snyksec/status/1480286811482206216?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet)
- [source3](https://security.snyk.io/vuln/SNYK-JS-COLORS-2331906)
This PR pins the color package to `1.4.0` as advised on the [snyk page](https://snyk.io/blog/open-source-maintainer-pulls-the-plug-on-npm-packages-colors-and-faker-now-what/)
* **What is the new behavior (if …
> fix: pin colors@1.4.0 to fix security vuln

- packages/finder/package.json
- packages/html-reporter/package.json
- yarn.lock
Fix
Using `"colors": "^1.4.0"` triggers the following mess: https://thenewstack.io/the-kik-kerfuffle/
Reverting to `"colors": "1.4.0"` will at least allow the module to work until `colors.js` is fixed or replaced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/504)
> Fast fix for the colors.js mess

- packages/core/src/statistic.ts
- packages/jscpd/src/index.ts
This is a chore fix, just removed the unused constructor and options that have not been used in the `Statistic` class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/507)
> fix: Drop unused constructor

- packages/finder/src/files.ts
Fix https://github.com/kucherenko/jscpd/issues/481
I allow the `noSymlinks` option to exclude the symlink itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/520)
> Exclude symlinks when noSymlinks is true

- packages/finder/__tests__/in-files-detector.test.ts
- packages/finder/package.json
https://github.com/kucherenko/jscpd/runs/5976675334?check_suite_focus=true
```
yarn run v1.22.18
$ run-s build test cov:html cov:check
$ lerna run build
lerna notice cli v3.20.2
lerna info ci enabled
lerna info Executing command in 8 packages: "yarn run build"
lerna ERR! yarn run build exited 2 in '@jscpd/badge-reporter'
lerna ERR! yarn run build stdout:
$ yarn clean && yarn compile
$ rm -rf ./dist
$ tsc -p tsconfig.build.json
Error: src/index.ts(2,25): error TS2307: Cannot find module '@jscpd/finder'.
```
I do the following in `@jscpd/finder` to get rid of the above error:
* Change `main` and `types` in `package.json` to `src/index` (Revert part of  https://github.com/kucherenko/jscpd/commit/5d7bace6d57dc1afd8a8b1b65943c5eaae62671c )
* Set no parameters in `Statistic` (The missing …
> fix: @jscpd/finder

- .github/workflows/nodejs.yml
Node.js versions of `jscpd CI` contain EOL versions and do not contain new versions.
Therefore, I change Node.js versions of `jscpd CI` to the following:
* 10.x: Delete due to EOL
* 13.x: Delete due to EOL
* 16.x: Add active LTS
* 17.x: Add current version
FYI: https://nodejs.org/en/about/releases/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/522)
> Update Node.js versions of jscpd CI

- .github/workflows/nodejs.yml
Bumps GitHub Actions to their latest major versions. Main change is they're now using Node 16 instead of 12, which is EOL at end of month.
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/526)
> ci: bump github actions

- packages/html-reporter/src/index.ts
[issue](https://github.com/kucherenko/jscpd/issues/476)
Escaped some special characters like '&', '<', '>', '`', '"', ''', '/'.  then html reporter rendering will not be infected by html tags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/533)
> fix: escape html tags in order to solve html reporter rendering problems

- README.md
This removes a link to a vscode extension under "Who uses jscpd."
The link 404s
The link is removed.
The extension seems to have been abandoned. The git repo for it hasn't had a commit since 2018.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/537)
> remove vscode extension link

- packages/jscpd/README.md
* **What kind of change does this PR introduce?** Docs.
* **What is the current behavior?**
The ``--min-tokens`` parameter through CLI seems inaccessible through config, but that's because it's called ``minTokens`` instead of ``min-tokens``.
The other properties I used are called verbatim as their CLI counterparts (format, reporters, output, absolute), as they are 1-word.
I've added a mention to it in the docs, since that's the easiest I could o, but if this is improved somehow, the docs may not need to reflect this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/540)
> Add mention to minTokens to the readme file

- packages/finder/src/files.ts
Fixes issue introduced in [v3.5.0](https://github.com/kucherenko/jscpd/tree/v3.5.0) by https://github.com/kucherenko/jscpd/commit/f514336d88aedce92c5e710d2904da9439ff12fb, where the `ignore` patterns are not ignored.
See https://github.com/kucherenko/jscpd/issues/496#issuecomment-1264700992 for more.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/547)
> Ensure that ignore config is respected

- packages/jscpd/README.md
This is a small update on the README, since JSON Reporter uses `duplicates` as the key of the array.
https://github.com/kucherenko/jscpd/blob/master/packages/finder/src/reporters/json.ts#L32
But the README shows an example JSON Report with `duplications` as the key
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/601)
> fix: spelling in JSON reporter example
