- src/jscpd.coffee
it's been bugging me for a little while...
Thanks for the great tool!
> Add a second n to scan*n*ing

- package.json
- src/tokenizer/TokenizerFactory.coffee
- test/fixtures/yaml/file1.yml
- test/fixtures/yaml/file2.yml
- test/reporters/json.test.coffee
- test/reporters/xml.test.coffee
- test/tokenizer/TokenizerFactory.test.coffee
Add yaml support with two ansible files as testing fixtures.
> feat(language): add yaml support

- src/cli/cli.coffee
- src/preprocessors/options.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/90)
> Fix for #82 - setting limit through config file is not working

- README.md
The command line options wasn't formatting nicely when rendered in the web browser. Forcing a table layout rather than a mixed table/list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/106)
> Update options table in README.md

- package.json
- src/tokenizer/TokenizerFactory.coffee
- test/fixtures/perl/file1.pl
- test/fixtures/perl/file1.pm
Hi,
Please consider adding basic support for Perl to your tool. This set of changes seems to work for me so far.
Cheers,
qyz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/105)
> Add basic support for perl

- src/cli/cli.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/125)
> Fix a couple spelling errors.

- README.md
- src/tokenizer/TokenizerCodeMirror.coffee
- src/tokenizer/TokenizerFactory.coffee
- test/fixtures/kotlin/file1.kt
- test/fixtures/kotlin/file2.kt
fixture files were auto-converted from java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/142)
> added Kotlin support

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/171)
> doc(readme) add link to old version of jscpd

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/174)
> 1.0.0 alpha

- README.md
* **What kind of change does this PR introduce?** Readme typo fix
* **What is the current behavior?** N/A
* **What is the new behavior (if this is a feature change)?** N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/232)
> fix(readme): fix typo in readme

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/244)
> fix(readme): fixes screenshot url

- package-lock.json
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/295)
> Greenkeeper/typedoc 0.15.3

- package-lock.json
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/297)
> Greenkeeper/snyk 1.251.1

- package-lock.json
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/301)
> Greenkeeper/ts node 8.5.3

- package-lock.json
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/303)
> Greenkeeper/snyk 1.252.0

- package-lock.json
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/305)
> Greenkeeper/ts node 8.5.4

- package-lock.json
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/309)
> Greenkeeper/snyk 1.257.0

- package-lock.json
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/308)
> Greenkeeper/typedoc 0.15.4

- package.json
- yarn.lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/367)
> fix: 🐛 wrong license

- packages/jscpd/src/init/cli.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/368)
> fix: update config file name in usage

- packages/jscpd/README.md
Fixed an issue on line 491
There is no break on code. Nothing to report, along the issue on line 491 
There is no break on code
Nothing to declare
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/395)
> Semantic issue on line 491

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/397)
> typo in readme: slower that --> slower than

- README.md
Add Mega-Linter also in main README  "Who uses JSCPD" section
Documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/409)
> Add Mega-Linter also in main README

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/480)
Much better now:
> Improves README with npm `svg` badge

- fixtures/ignore-pattern/file_1.js
- fixtures/ignore-pattern/file_2.js
- packages/core/src/interfaces/options.interface.ts
- packages/jscpd/README.md
- packages/jscpd/__tests__/options.test.ts
- packages/jscpd/src/init/cli.ts
- packages/jscpd/src/options.ts
- packages/tokenizer/src/tokenize.ts
feature
Adds ability to ignore code blocks matching the regexp patterns
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/469)
> Adds --ignore-pattern option (closes #435)

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- package.json
Check version publishing from ci
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/632)
> ci(actions): change github actions flow

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
Update actions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/636)
> ci(actions): update version of steps in the actions

- apps/jscpd/CHANGELOG.md
- apps/jscpd/package.json
- apps/jscpd/src/init/reporters.ts
- packages/sarif-reporter/CHANGELOG.md
- packages/sarif-reporter/package.json
- pnpm-lock.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kucherenko/jscpd/638)
> chore(sarif): add changelog for sarif
